spring:
  profiles:
    active: a
  datasource:
      data-source: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3366/db_person
      username: root
      password: 111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true